sudo: required

language: generic

services:
  - docker

before_install:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t sergkh/docker-etcd-registrator .

script:
  - docker tag sergkh/docker-etcd-registrator:0.1 
  - docker tag sergkh/docker-etcd-registrator:latest     
  - docker push sergkh/docker-etcd-registrator